## Numpy array and basics

In [12]:
import numpy as np

creating array from List

In [13]:
arr1d=np.array([1,2,3])
print(f"1D Array : {arr1d}")

arr2d=np.array([[1,2,3],[1,2,3]])
print(f"2D Array : {arr2d}")

1D Array : [1 2 3]
2D Array : [[1 2 3]
 [1 2 3]]


### List vs Numpy Array

In [14]:
py_list=[1,2,3]
print(f"Python list Multiplication :{py_list * 2}")

np_array=np.array([1,2,3])
print(f"Python array Multiplication : {np_array * 2}")

import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time : ", time.time()-start)

start=time.time()
np_array=np.array(10000000)*2
print("\n Numpy operation time:", time.time() - start)

Python list Multiplication :[1, 2, 3, 1, 2, 3]
Python array Multiplication : [2 4 6]

 List operation time :  0.08443593978881836

 Numpy operation time: 0.0


### creating arrays from scratch

In [15]:
zeros=np.zeros((3,4))
print(f" zeros array : {zeros}")

ones=np.ones((2,3))
print(f" ones array : {ones}")

full=np.full((4,4), 7)
print(f"full array :{full}")

random=np.random.random((3,4))
print(f"random array : {random}")

sequence=np.arange(0,10,2)
print(f"random array : {sequence}")


 zeros array : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 ones array : [[1. 1. 1.]
 [1. 1. 1.]]
full array :[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array : [[0.24456449 0.89163619 0.19385688 0.32383624]
 [0.74897384 0.29749977 0.43205163 0.3566212 ]
 [0.44792871 0.4196294  0.84439808 0.39528317]]
random array : [0 2 4 6 8]


### Vector Matrix and Tensor

In [16]:
vector=np.array([1,2,3])
print(f"Vector : {vector}")

matrix=np.array([[1,2,3],
                 [1,2,4]])
print(f"Matrix : {matrix}")

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print(f"Tensor : {tensor}")

Vector : [1 2 3]
Matrix : [[1 2 3]
 [1 2 4]]
Tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [17]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(f"Shape : {arr.shape}")
print(f"Dimension : {arr.ndim}")
print(f"Size : {arr.size}")
print(f"DType : {arr.dtype}")

Shape : (2, 3)
Dimension : 2
Size : 6
DType : int64


In [19]:
arr=np.arange(12)
print(f"Original array {arr}")

reshaped=arr.reshape((3,4))
print(f"Reshaped array : {reshaped}")

flattened= reshaped.flatten()
print(f"Flattened array : {flattened}")

#Raveled (returns view, instead of copy )
raveled=reshaped.ravel()
print(f"Raveled array : {raveled}")

#Transpose
Transpose=reshaped.T
print(f"Transpose array {Transpose}")

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
