## Numpy array Operations

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Basic Slicing :{arr[2:7]}")
print(f"With Step :{arr[1:8:2]}")
print(f"Negative Slicing :{arr[-3]}")

Basic Slicing :[3 4 5 6 7]
With Step :[2 4 6 8]
Negative Slicing :8


In [4]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(f"Specific element :{arr_2d[1, 2]}")
print(f"Entire row :{arr_2d[1]}")
print(f"Entire column :{arr_2d[:, 1]}")

Specific element :6
Entire row :[4 5 6]
Entire column :[2 5 8]


## Sorting 

In [5]:
import numpy as np

unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print(f"Sorted array: {np.sort(unsorted)}")

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print(f"Sorted 2D array (column-wise):\n{np.sort(arr_2d_unsorted, axis=0)}")


Sorted array: [1 1 2 3 4 5 6 9]
Sorted 2D array (column-wise):
[[1 1]
 [2 2]
 [3 3]]


## Filter

In [6]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers %2==0]
print(f"Even numbers :{even_number}")

Even numbers :[ 2  4  6  8 10]


## Filters with Mask

In [ ]:
mask=numbers>5
print(f"Numbers greater than 5 : {numbers[mask]}")

Numbers greater than : [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [10]:
indices=[0,2,4,7] #index postions
print(numbers[indices])

where_results=np.where(numbers>5)
print(f"Numbers Where, {numbers[where_results]}")

[1 3 5 8]
Numbers Where, [ 6  7  8  9 10]


In [ ]:
condition_array=np.where(numbers>5, numbers*10, numbers) #if-else kind of (if condition, do this, else this)
print(condition_array)

[  1   2   3   4   5  60  70  80  90 100]


## Adding and Removing data 

In [13]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibility

In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6, 7])
c=np.array([7,8,9])
print(f"Compatibility  check : {a.shape==b.shape}")

Compatibility  check : False


In [20]:
original=np.array([[1,2],[3,4]])
new_row=np.array([5,6])

with_new_row=np.vstack((original, new_row))#np.vstack adds new row
print(original)
print(with_new_row)

new_col=np.array(([5],[5]))
with_new_col=np.hstack((original, new_col))#np.hstack adds new column
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 5]]


In [22]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr, 2)#deletes 2nd index val in array
print(f"Array after deletion : {deleted}")

Array after deletion : [1 2 4 5]
